// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFVqxD4yRMI-ARrsic2xFQdTP7TKd_7uY',
    appId: '1:25154784684:web:e120ab182084add11a7e09',
    messagingSenderId: '25154784684',
    projectId: 'newfamly-8d04d',
    authDomain: 'newfamly-8d04d.firebaseapp.com',
    storageBucket: 'newfamly-8d04d.appspot.com',
    measurementId: 'G-BGXVED6JXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXSyNHFSN6T_9W_mfVMXXHYzKBjTH24E0',
    appId: '1:25154784684:android:8f52d642152c12651a7e09',
    messagingSenderId: '25154784684',
    projectId: 'newfamly-8d04d',
    storageBucket: 'newfamly-8d04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgJRGtCzv76cI-mmSGt6eFKqU9wqiXWa8',
    appId: '1:25154784684:ios:d749f32bfe53df071a7e09',
    messagingSenderId: '25154784684',
    projectId: 'newfamly-8d04d',
    storageBucket: 'newfamly-8d04d.appspot.com',
    iosClientId: '25154784684-oienh69e7e8q4si4ig7f6p9dfnda8ac9.apps.googleusercontent.com',
    iosBundleId: 'com.example.newfamly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgJRGtCzv76cI-mmSGt6eFKqU9wqiXWa8',
    appId: '1:25154784684:ios:c5ccce14052234601a7e09',
    messagingSenderId: '25154784684',
    projectId: 'newfamly-8d04d',
    storageBucket: 'newfamly-8d04d.appspot.com',
    iosClientId: '25154784684-k6fg5cb4g9e60j5r9d9oc1bs35048su3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newfamly.RunnerTests',
  );
}
